#Dockerfile per Host Ubuntu

FROM ubuntu:latest

LABEL maintainer "alf_99@hotmail.it"

RUN apt-get update && apt-get install -y \
bridge-utils \
net-tools \
iputils-ping \
nmap \
hping3 \
ftp 

CMD echo "Ubuntu Host"
